### ISSUE TITLE
JSON appears invalid

### ISSUE THREAD

**Issue by aofarrel** [genome/qc-analysis-pipeline#51]
The workflow is named SingleSampleQc with WholeGenomeSingleSampleQc.wdl, while the JSON refers to WholeGenomeSingleSampleQc. For the JSON to autofill on Terra, it needs to match the name of the workflow rather than the filename of the WDL.

In addition, the following required inputs are missing from the JSON.
* is_wgs
* ref_cache
* coverage_interval_list -- but there is wgs_coverage_interval_list

Currently testing a best guess on these inputs, will open a PR if it passes on Terra.

**Comment by aofarrel** [comment]
Attempted the following but "worker failed to complete the task" (this was attempt 4, after the 3 preemptible attempts, so it doesn't seem to be due to a prempted disk). Based on the logs it looks like some files are not localizing; maybe one of the links is incorrect?

> {
>   "SingleSampleQc.input_bam": "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam",
>   "SingleSampleQc.input_bam_index": "gs://genomics-public-data/platinum-genomes/bam/NA12878_S1.bam.bai",
>   "SingleSampleQc.is_wgs": false,
>   "SingleSampleQc.base_name": "NA12878",
>   "SingleSampleQc.contamination_sites_ud": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.contam.UD",
>   "SingleSampleQc.contamination_sites_bed": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.contam.bed",
>   "SingleSampleQc.contamination_sites_mu": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.contam.mu",
>   "SingleSampleQc.ref_cache": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta",
>   "SingleSampleQc.ref_dict": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.dict",
>   "SingleSampleQc.ref_fasta": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta",
>   "SingleSampleQc.ref_fasta_index": "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.fasta.fai",
>   "SingleSampleQc.coverage_interval_list": "gs://gcp-public-data--broad-references/hg38/v0/wgs_coverage_regions.hg38.interval_list",
>   "SingleSampleQc.preemptible_tries": 3
> }

**Comment by jasonwalker80** [comment]
Hello @aofarrel,

It doesn't surprise me that we left the JSON in an incomplete state. We've been executing off a branch for AnVIL and the `WES` features were some of the last changes pushed to master before we focused on the branch. Hence the `is_wgs` input (and either exome or wgs intervals as optional inputs). The ref_cache was also a recent change.

Here is an example from a recent execution of the `no_validatesamfile` branch that we have been working from. The inputs should be the same when running on the `master` branch.

```
SingleSampleQc.CollectHsMetrics.memory_multiplier | "${2}"
-- | --
SingleSampleQc.CollectRawWgsMetrics.memory_multiplier | "${4}"
SingleSampleQc.base_name | "${this.fixed_manifest_sample_id}"
SingleSampleQc.contamination_sites_bed | "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.contam.bed"
SingleSampleQc.contamination_sites_mu | "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.contam.mu"
SingleSampleQc.contamination_sites_ud | "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.contam.UD"
SingleSampleQc.coverage_interval_list | "gs://gcp-public-data--broad-references/hg38/v0/wgs_coverage_regions.hg38.interval_list"
SingleSampleQc.input_bam | "${this.cram}"
SingleSampleQc.is_wgs | "${true}"
SingleSampleQc.preemptible_tries | "${3}"
SingleSampleQc.ref_cache | "gs://gcp-public-data--broad-references/hg38/v0/Homo_sapiens_assembly38.ref_cache.tar.gz"
SingleSampleQc.ref_dict | "${workspace.referenceData_hg38_ref_dict}"
SingleSampleQc.ref_fasta | "${workspace.referenceData_hg38_ref_fasta}"
SingleSampleQc.ref_fasta_index | "${workspace.referenceData_hg38_ref_fasta_index}"
```
