### ISSUE TITLE
move to canonical repo/rename

### ISSUE THREAD

**Issue by jasonwalker80** [genome/qc-analysis-pipeline#6]

**Comment by jasonwalker80** [comment]
@acoffman do we need to rename or move anything? Can this be resolved?

**Comment by acoffman** [comment]
@jasonwalker80 This is probably good enough for now; once this is "blessed" it maybe should go under the anvil org or someplace more official, but that's probably one of the last things that needs to happen.

**Comment by jasonwalker80** [comment]
After going through a test, I'm going to leave this open. If nothing more than a reminder to rename the branch names in the WDL imports before we have a final tagged release.
